version: '3'
services:
  tsmart:
    container_name: tsmart
    image: britkat/tsmart:0.91
    restart: unless-stopped
    environment:
      - IP_Address=xx.xx.xx.xx
      - MQTT_Address=xx.xx.xx.xx
      - self_run_timer=60
    network_mode: host
